#!/usr/bin/env bash
# 将 append-only 的 v45-entry.evidence  rollup 为 canonical（每键取最后一次赋值）.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
SRC="$ROOT/lab/nano-lisp-jit/.build/v45-entry.evidence"
OUT="$ROOT/lab/nano-lisp-jit/.build/v45-entry.evidence.canonical"
cd "$ROOT"
test -f "$SRC" || { echo "v45-evidence-canonical=skip missing"; exit 0; }
python3 - <<'PY' "$SRC" "$OUT"
import sys
from pathlib import Path
src, out = Path(sys.argv[1]), Path(sys.argv[2])
kv = {}
for line in src.read_text().splitlines():
    line = line.strip()
    if not line or "=" not in line:
        continue
    k, _, v = line.partition("=")
    kv[k] = v
# 分组输出：goal → mindmap → selfhost → tier → 其他
order_prefix = (
    "v45.goal.", "v45.mindmap.", "v45.selfhost.", "v45.onion.",
    "v45.tier5.", "v45.physical.", "v45.scoped", "v45.endgame",
    "v45.release", "v45.warehouse", "v45.boundary.", "v45.wave",
)
def sort_key(k):
    for i, p in enumerate(order_prefix):
        if k.startswith(p):
            return (i, k)
    return (99, k)
lines = [
    "# v45-entry.evidence.canonical — generated by v45-evidence-canonical.sh",
    f"# source_lines={sum(1 for _ in src.read_text().splitlines())} unique_keys={len(kv)}",
    "",
]
for k in sorted(kv.keys(), key=sort_key):
    lines.append(f"{k}={kv[k]}")
out.write_text("\n".join(lines) + "\n")
print(f"v45-evidence-canonical=ok keys={len(kv)} out={out}")
PY
