; shell-repl — VM loop: nano read-line + libc:system (Phase 5).
(module
  (import read-line "nano" "read-line" "i32(ptr,i32)")
  (import system "libc" "system" "i32(ptr)")
  (import strcmp "libc" "strcmp" "i32(ptr,ptr)")
  (const buf "                                                                                                                                ")
  (const cmd-exit "exit")
  (const cmd-quit "quit")
  (main
    (resolve read-line)
    (resolve system)
    (resolve strcmp)
    (label loop)
    (call read-line buf 128)
    (eq-i64 0)
    (branch done)
    (call strcmp buf cmd-exit)
    (eq-i64 0)
    (branch done)
    (call strcmp buf cmd-quit)
    (eq-i64 0)
    (branch done)
    (call system buf)
    (eq-i64 0)
    (branch loop)
    (label done)))
