; shell-repl-fgets — VM loop: libc fgets + stdin addr + libc:system (Phase 7).
(module
  (import fgets "libc" "fgets" "ptr(ptr,i32,ptr)")
  (import stdin "libc" "stdin" "addr")
  (import system "libc" "system" "i32(ptr)")
  (import strcmp "libc" "strcmp" "i32(ptr,ptr)")
  (const buf "                                                                                                                                ")
  (const cmd-exit "exit")
  (const cmd-quit "quit")
  (main
    (resolve fgets)
    (resolve stdin)
    (resolve system)
    (resolve strcmp)
    (label loop)
    (call fgets buf 128 stdin)
    (is-null-ptr)
    (branch done)
    (call strcmp buf cmd-exit)
    (eq-i64 0)
    (branch done)
    (call strcmp buf cmd-quit)
    (eq-i64 0)
    (branch done)
    (call system buf)
    (eq-i64 0)
    (branch loop)
    (label done)))
