; Multi-function pointer smoke: preserve ptr return kind across a local call.
(module
  (func maybe-null
    (null-ptr))
  (func offset-ptr
    (null-ptr)
    (add-ptr 1))
  (func offset-bits
    (call offset-ptr)
    (ptr-to-u64))
  (func roundtrip-ptr
    (null-ptr)
    (add-ptr 8)
    (sub-ptr 8))
  (main
    (call maybe-null)
    (expect null)
    (is-null-ptr)
    (branch ptr-null)
    (u64 1)
    (expect 999)
    (label ptr-null)
    (call maybe-null)
    (is-nonnull-ptr)
    (expect false)
    (call offset-ptr)
    (expect nonnull)
    (is-nonnull-ptr)
    (expect true)
    (call offset-bits)
    (expect 1)
    (u64-to-ptr)
    (expect nonnull)
    (call roundtrip-ptr)
    (expect null)
    (is-null-ptr)
    (expect true)
    (bool false)
    (not-bool)
    (expect true)))
