; v4.5 release 100% DONE — onion-lisp-only 主门禁 + endgame evidence (plan 无 .c).
(bootstrap
  (file-size "lab/nano-lisp-jit/v4.5/PROGRESS.md")
  (file-size "lab/nano-lisp-jit/v4.5/EVAL.md")
  (file-size "lab/nano-lisp-jit/v4.5/REFLECTION.md")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-endgame-100.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-onion-lisp-only.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-onion-tdd.lisp")
  (file-size "lab/nano-lisp-jit/.build/v45-entry.evidence")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.endgame.100" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.release.100" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.scoped.100" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.tier5.100" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.physical.zero_c" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.goal.mindmap_tree.100" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.goal.onion_mindmap.unified.100" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.mindmap.tree.coupled" "1")
  (file-hash "lab/nano-lisp-jit/.build/nano-jit/nano-jit.com")
  (file-hash "lab/nano-lisp-jit/.build/v45-onion-lo-ape.com"))
