; v4.5 S8: factory matrix — all发行面 bootstrap-v45 plans indexed (one diffuse plan).
(bootstrap
  (file-size "lab/nano-lisp-jit/v4.5/DECISION.md")
  (file-size "lab/nano-lisp-jit/v4.5/ONION-TDD.md")
  (file-size "lab/nano-lisp-jit/v4.5/SELFHOST.md")
  (file-size "lab/nano-lisp-jit/v4.5/DIFFUSE-WAVE2.md")
  (file-size "lab/nano-lisp-jit/v4.5/CONCURRENT-IMPL.md")
  (file-size "lab/nano-lisp-jit/v4.5/PARALLEL.md")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-entry.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-verify-smoke.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-verify-core.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-v4-handoff.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-verify-all.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-build-slice-genesis.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-build-slice-lisp.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-selfhost-chain.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-selfhost-modules-full.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-selfhost-regenesis.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-onion-tdd.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-boundary-probe.lisp")
  (file-size "lab/nano-lisp-jit/lisp/bootstrap/bootstrap-v45-factory-matrix.lisp")
  (file-hash "lab/nano-lisp-jit/scripts/v45-com-verify.sh")
  (file-hash "lab/nano-lisp-jit/scripts/v45-wave2-converge.sh"))
