; Wave57 W2: lispjit.c archive 诚实 — active 已迁 retired/ · sh/py 仍存.
(bootstrap
  (file-size "lab/nano-lisp-jit/v4.5/HONEST-REMAINING.md")
  (file-size "lab/nano-lisp-jit/v4.5/DIFFUSE-WAVE57.md")
  (file-size "lab/nano-lisp-jit/retired/lispjit.c.archived")
  (file-hash "lab/nano-lisp-jit/retired/lispjit.c.archived")
  (file-size "lab/nano-lisp-jit/retired/scripts/v45-wave57-lispjit-c-delete-converge.sh")
  (file-size "lab/nano-lisp-jit/retired/scripts/v45-wave56-zero-cpysh-target-converge.sh")
  (file-size "lab/nano-lisp-jit/retired/tools/mindmap-dp-v45.py")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.runner.lispjit_c_active_deleted" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.honest.lispjit_c_retired" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.honest.host_sh_retired" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.honest.tools_py_maintenance_only" "1")
  (results-min "lab/nano-lisp-jit/.build/v45-entry.evidence" "v45.honest.zero_cpysh_remaining" "1")
  (file-hash "lab/nano-lisp-jit/v4.5/DIFFUSE-WAVE57.md"))
